# Generated by Django 6.0.7 on 2026-07-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('payee', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
                ('outflow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inflow', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
